[repo]
name = "forge.domain_randomization"

[repo_publish_exts]
enabled = true
repo_name = "forge.domain_randomization"
configs = ["release"]
platforms = ["linux-x86_64"]
python_tag = "cp310"
pack_extension = true
publish_verification = true
signing.enabled = false

[repo_publish_exts.exts]
include = ["forge.domain_randomization"]
exclude = []


[repo_test]
enabled = true

[repo_test.suites.main]
kind = "python"
path = "extensions/forge.domain_randomization/tests"
